-- @description Anibla scripts
-- @author mrtnz
-- @version 0.5.60
-- @provides 
--   [main] .
--   [main] mrtnz_insert text item by region under mouse.lua
--   [main] mrtnz_Create subproject for selected tracks.lua
--   [main] mrtnz_Create Timer Subproject.lua
--   [main] mrtnz_Load subprojects in current project.lua
--   [main] mrtnz_insert update regions.lua
--   [main] mrtnz_subtitles manager.lua
--   [main] mrtnz_toggle show grid line.lua
--   [main] mrtnz_calculate recorded.lua
--   [main] mrtnz_calculate long media.lua
--   [main] mrtnz_calculate excel.lua
--   [main] mrtnz_glue regions in time selection.lua
--   [main] mrtnz_insert update dubbers.lua
--   [main] mrtnz_subtitle_hotkeys.lua
--   [main] mrtnz_subtitle_session.lua
--   [main] mrtnz_subtitle_sync.lua
--   [main] mrtnz_subtitle_ui.lua
--   [main] mrtnz_subtitle_editor_main.lua
--   [main] mrtnz_Note manager.lua
--   create_exc.py
--   Reateam_RPP-Parser.lua
--   mrtnz_srtass-parser.lua
--   mrtnz_utils.lua
--   clnew.ttc

local nothing